config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    get :version_histories, on: :member
    resources :comments
  end
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "projects#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :project
  belongs_to :user

  validates :body, presence: true
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :version_histories, dependent: :destroy

  enum :status, {
    pending: "pending",
    in_progress: "in_progress",
    completed: "completed"
  }

  validates :name, presence: true
  validates :description, presence: true
  validates :status, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :projects
  has_many :comments
end

app/models/version_history.rb
class VersionHistory < ApplicationRecord
  belongs_to :project

  enum :version_type, {
    comment: "comment",
    status_change: "status_change",
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  # POST /comments or /comments.json
  def create
    @project = Project.find(params[:project_id])
    @comment = @project.comments.create(comment_params)

    respond_to do |format|
      @comment.user = current_user
      if @comment.save
        @project.version_histories.create(version_type: :comment, title: "Comment added by #{current_user.first_name}", body: @comment.body)
        format.html { redirect_to @project, notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { redirect_to @project, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:body, :project_id, :user_id)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy version_histories ]
  before_action :authenticate_user!, only: %i[ new create edit update destroy ]
  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      @project.user = current_user
      if @project.save
        format.html { redirect_to @project, notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if params[:project][:status] != @project.status
        @project.version_histories.create(version_type: :status_change, title: "Status changed", body: "Status changed from #{@project.status.humanize} to #{params[:project][:status].humanize}")
      end
      if @project.update(project_params)
        format.html { redirect_to @project, notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy!

    respond_to do |format|
      format.html { redirect_to projects_path, status: :see_other, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def version_histories
    @version_histories = @project.version_histories
  end 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :description, :status, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/comments/_comment.html.slim
div id="#{dom_id comment}"
  div.p-3.border.rounded-lg.bg-gray-100
    p.font-semibold.text-gray-800
      strong Body:
      =< comment.body
    p.text-gray-800
      strong Commented by:
      =< comment.user.first_name

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Project Converstaion" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/projects/_form.html.slim
div.space-y-12
  = form_with(model: project) do |form|
    - if project.errors.any?
      div style="color: red"
        h2 = "#{pluralize(project.errors.count, "error")} prohibited this project from being saved:"
      ul
        - project.errors.each do |error|
          li = error.full_message
    div.mt-10.grid.grid-cols-1.gap-x-6.gap-y-8.sm:grid-cols-6
      div.sm:col-span-4
        = form.label :name, class: "block text-sm/6 font-medium text-gray-900"
        div.mt-2
          = form.text_field :name, class: "flex items-center rounded-md bg-white pl-3 outline-1 -outline-offset-1 outline-gray-300 focus-within:outline-2 focus-within:-outline-offset-2 focus-within:outline-indigo-600"

      div.sm:col-span-4
        = form.label :description, class: "block text-sm/6 font-medium text-gray-900"
        div.mt-2
          = form.text_area :description, class: "flex items-center rounded-md bg-white pl-3 outline-1 -outline-offset-1 outline-gray-300 focus-within:outline-2 focus-within:-outline-offset-2 focus-within:outline-indigo-600"

      div.sm:col-span-4
        = form.label :status, class: "block text-sm/6 font-medium text-gray-900"
        div.mt-2
          = form.select :status, Project.statuses.keys.map { |status| [status.humanize, status] }, {}, class: "flex items-center rounded-md bg-white pl-3 outline-1 -outline-offset-1 outline-gray-300 focus-within:outline-2 focus-within:-outline-offset-2 focus-within:outline-indigo-600"

      div.sm:col-span-4 
        = form.submit 'Submit', class: "rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"

app/views/projects/_project.html.slim
div id="#{dom_id project}"
  p
    strong Name:
    =< project.name
  p
    strong Description:
    =< project.description
  p
    strong Status:
    =< project.status&.humanize

app/views/projects/_version_history.html.slim
div id="#{dom_id version_history}"
  div.p-3.border.rounded-lg.bg-gray-100
    p.font-semibold.text-gray-800
      =< version_history.title
    p.text-gray-800
      =< version_history.body

app/views/projects/edit.html.slim
div.space-y-12  
  h1 Editing project

  == render "form", project: @project

  br

div
  => link_to "Show this project", @project, class: "rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
  '|
  =< link_to "Back to projects", projects_path, class: "text-white bg-gray-800 hover:bg-gray-900 focus:outline-none focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-700 dark:border-gray-700"

app/views/projects/index.html.slim
div.flex.flex-col
  div.mb-12 
    p style="color: green" = notice

  div.space-y-6
    h1 Projects

    #projects
    - @projects.each do |project|
      == render project
      p
        => link_to "View project", project
        '|
        =< link_to "Version History", version_histories_project_path(project)

div.space-y-6
  - if current_user.present?
    = link_to "New project", new_project_path, class: "rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"

app/views/projects/new.html.slim
div.space-y-12
  h1 New project

  == render "form", project: @project

  br

div
  = link_to "Back to projects", projects_path, class: "text-white bg-gray-800 hover:bg-gray-900 focus:outline-none focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-700 dark:border-gray-700"

app/views/projects/show.html.slim
div.flex.flex-col
  div.mb-12 
    p style="color: green" = notice
  div
    == render @project

  div.mt-4
    - if current_user == @project.user
      => link_to "Edit this project", edit_project_path(@project), class: "rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
      '|
    =< link_to "Back to projects", projects_path, class: " text-white bg-gray-800 hover:bg-gray-900 focus:outline-none focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-700 dark:border-gray-700"
    '|
    =< link_to "Version History", version_histories_project_path(@project), class: "rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"  
    - if current_user == @project.user
      div.mt-4  
        = button_to "Destroy this project", @project, method: :delete, class: "rounded-md bg-red-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-red-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-red-600"


  div.mt-12
    div
      h2 Comments
      - if @project.comments.any?
        div.max-w-lg.mx-auto.p-4.bg-white.shadow-md.rounded-lg
          div.space-y-4
            - @project.comments.each do |comment|
              == render comment
      - if current_user.present?
        div.mt-4.space-y-6
          = form_with(model: [@project, @project.comments.build]) do |form|
            = form.text_area :body, class: "flex items-center rounded-md bg-white pl-3 outline-1 -outline-offset-1 outline-gray-300 focus-within:outline-2 focus-within:-outline-offset-2 focus-within:outline-indigo-600" 
            = form.submit "Add Comment", class: "mt-2 rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"

app/views/projects/version_histories.html.slim
div.mb-12
  = link_to "Back to projects", project_path(@project), class: "text-white bg-gray-800 hover:bg-gray-900 focus:outline-none focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-700 dark:border-gray-700"
div.max-w-lg.mx-auto.p-4.bg-white.shadow-md.rounded-lg
  div.space-y-4
    - @project.version_histories.each do |version_history|
      == render partial: "projects/version_history", locals: { version_history: version_history }

app/views/shared/_navbar.html.slim
nav.bg-gray-800
  .mx-auto.max-w-7xl.px-2.sm:px-6.lg:px-8
    .relative.flex.h-16.items-center.justify-between
      .absolute.inset-y-0.left-0.flex.items-center.sm:hidden
        button.relative.inline-flex.items-center.justify-center.rounded-md.p-2.text-gray-400.hover:bg-gray-700.hover:text-white.focus:ring-2.focus:ring-white.focus:outline-none.focus:ring-inset type="button" aria-controls="mobile-menu" aria-expanded="false"
          span.absolute.-inset-0.5
          span.sr-only Open main menu
          svg.block.size-6 fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true" data-slot="icon"
            path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5"
          svg.hidden.size-6 fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true" data-slot="icon"
            path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12"
      
      .flex.flex-1.items-center.justify-center.sm:items-stretch.sm:justify-start
        .flex.shrink-0.items-center
          img.h-8.w-auto src="https://tailwindui.com/plus/img/logos/mark.svg?color=indigo&shade=500" alt="Your Company"
        .hidden.sm:ml-6.sm:block
          .flex.space-x-4
            = link_to "Projects", projects_path, class: "rounded-md bg-gray-900 px-3 py-2 text-sm font-medium text-white"
            - if current_user.present?
              = link_to "sign out", destroy_user_session_path, method: :delete, data: { turbo_method: :delete }, class: "rounded-md bg-gray-900 px-3 py-2 text-sm font-medium text-white"
            - else
              = link_to "sign in", new_user_session_path, class: "rounded-md bg-gray-900 px-3 py-2 text-sm font-medium text-white"  

  .sm:hidden#mobile-menu
    .space-y-1.px-2.pt-2.pb-3
      a.block.rounded-md.bg-gray-900.px-3.py-2.text-base.font-medium.text-white href="#" aria-current="page" Dashboard
      a.block.rounded-md.px-3.py-2.text-base.font-medium.text-gray-300.hover:bg-gray-700.hover:text-white href="#" Team
      a.block.rounded-md.px-3.py-2.text-base.font-medium.text-gray-300.hover:bg-gray-700.hover:text-white href="#" Projects
      a.block.rounded-md.px-3.py-2.text-base.font-medium.text-gray-300.hover:bg-gray-700.hover:text-white href="#" Calendar